

set(libgfx_SOURCES
	sources/Buffers.cpp
sources/Buffers.h
sources/Common.cpp
sources/Common.h
sources/Core/GFXAPI.cpp
sources/Core/GFXAPI.h
sources/Core/SwapChain.cpp
sources/Core/SwapChain.h
sources/DescriptorBindFrag.h
sources/DescriptorBindVert.h
sources/Descriptors.cpp
sources/Descriptors.h
sources/GraphicApi.cpp
sources/GraphicAPI.h
sources/Image.cpp
sources/Image.h
sources/Initializers.hpp
sources/LightManager.cpp
sources/LightManager.h
sources/LowRenderer/Camera.cpp
sources/LowRenderer/Camera.h
sources/LowRenderer/Light.cpp
sources/LowRenderer/Light.h
sources/LowRenderer/Model/Mesh.h
sources/LowRenderer/Model/Model.cpp
sources/LowRenderer/Model/Model.h
sources/LowRenderer/Model/Vertex.h
sources/Pipeline.cpp
sources/Pipeline.h
sources/RenderingManager.cpp
sources/RenderingManager.h
sources/Renderpass.cpp
sources/Renderpass.h
sources/Resources/ActorComponentsData.cpp
sources/Resources/ActorComponentsData.h
sources/Resources/ActorComponentsDataForUI/ActorCameraCompData.cpp
sources/Resources/ActorComponentsDataForUI/ActorCameraCompData.h
sources/Resources/ActorComponentsDataForUI/ActorLightCompData.cpp
sources/Resources/ActorComponentsDataForUI/ActorLightCompData.h
sources/Resources/ActorComponentsDataForUI/ActorPhysicCompData.cpp
sources/Resources/ActorComponentsDataForUI/ActorPhysicCompData.h
sources/Resources/ActorComponentsDataForUI/ActorScriptCompData.cpp
sources/Resources/ActorComponentsDataForUI/ActorScriptCompData.h
sources/Resources/ActorComponentsDataForUI/ActorSoundCompData.cpp
sources/Resources/ActorComponentsDataForUI/ActorSoundCompData.h
sources/Resources/ActorComponentsDataForUI/ActorStaticMeshCompData.cpp
sources/Resources/ActorComponentsDataForUI/ActorStaticMeshCompData.h
sources/Resources/ActorComponentsDataForUI/ActorTransformCompData.cpp
sources/Resources/ActorComponentsDataForUI/ActorTransformCompData.h
sources/Resources/FileAsset.cpp
sources/Resources/FileAsset.h
sources/Resources/FolderAsset.cpp
sources/Resources/FolderAsset.h
sources/Resources/HashString.h
sources/Resources/Resource.h
sources/Resources/SavedData.cpp
sources/Resources/SavedData.h
sources/Resources/TextureLoader.cpp
sources/Resources/TextureLoader.h
sources/Resources/UITexture.cpp
sources/Resources/UITexture.h
sources/Shader.h
sources/SurfaceDescriptor.h
sources/TextureSampler.h
sources/UI/UIWidgetButton.cpp
sources/UI/UIWidgetButton.h
sources/UI/UIWidgetImage.cpp
sources/UI/UIWidgetImage.h
sources/UI/UIWidgets.cpp
sources/UI/UIWidgets.h
sources/UI/UIWidgetText.cpp
sources/UI/UIWidgetText.h
sources/UI/UIWindow.cpp
sources/UI/UIWindow.h
sources/UI/UIWindowManager.cpp
sources/UI/UIWindowManager.h
sources/UI/UIWindows/UIWindowBuild.cpp
sources/UI/UIWindows/UIWindowBuild.h
sources/UI/UIWindows/UIWindowComponents.cpp
sources/UI/UIWindows/UIWindowComponents.h
sources/UI/UIWindows/UIWindowFIleBrowser.cpp
sources/UI/UIWindows/UIWindowFIleBrowser.h
sources/UI/UIWindows/UIWindowMainToolBar.cpp
sources/UI/UIWindows/UIWindowMainToolBar.h
sources/UI/UIWindows/UIWindowUIInGamePreview.cpp
sources/UI/UIWindows/UIWindowUIInGamePreview.h
sources/UI/UIWindows/UIWindowViewportScene.cpp
sources/UI/UIWindows/UIWindowViewportScene.h
sources/UI/UIWindows/UIWindowWorldHierarchy.cpp
sources/UI/UIWindows/UIWindowWorldHierarchy.h
sources/VkDeleter.h
sources/Window/Window.cpp
sources/Window/Window.h
	)
